//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Forum
{
    public partial class List
    {
        /// <summary>
        /// phNew control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNew;

        /// <summary>
        /// pnlLoginHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginHint;

        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// rptThreads control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptThreads;
    }
}
