//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Forum
{
    public partial class New
    {
        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBody;

        /// <summary>
        /// btnPost control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPost;
    }
}
