//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Forum
{
    public partial class Thread
    {
        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// litAuthor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAuthor;

        /// <summary>
        /// rptPosts control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPosts;

        /// <summary>
        /// pnlReply control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlReply;

        /// <summary>
        /// txtBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBody;

        /// <summary>
        /// btnReply control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReply;

        /// <summary>
        /// pnlLoginHint control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginHint;
    }
}
