//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Account
{
    public partial class UserProfile
    {
        protected global::System.Web.UI.WebControls.Literal litUsername;
        protected global::System.Web.UI.WebControls.Literal litRole;
        protected global::System.Web.UI.WebControls.Label lblDetailsMsg;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.Button btnSaveDetails;
        protected global::System.Web.UI.WebControls.Label lblPasswordMsg;
        protected global::System.Web.UI.WebControls.TextBox txtCurrent;
        protected global::System.Web.UI.WebControls.TextBox txtNew;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmNew;
        protected global::System.Web.UI.WebControls.Button btnChangePassword;
    }
}
