//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest
{


    public partial class SiteMaster
    {

        /// <summary>
        /// HeadContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// phBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phBack;

        /// <summary>
        /// lnkBack control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;

        /// <summary>
        /// phStaff control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phStaff;

        /// <summary>
        /// phAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdmin;

        /// <summary>
        /// phMember control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMember;

        /// <summary>
        /// phNavMyProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNavMyProgress;

        /// <summary>
        /// phNavStudentProgress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phNavStudentProgress;

        /// <summary>
        /// phAnon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAnon;

        /// <summary>
        /// phUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phUser;

        /// <summary>
        /// lnkHello control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkHello;
    }
}
