//------------------------------------------------------------------------------
// <auto-generated>  Hand-written designer (no VS designer in this repo). </auto-generated>
//------------------------------------------------------------------------------
namespace Hardwarequest.Quiz
{
    public partial class Builder
    {
        protected global::System.Web.UI.WebControls.Literal litHeading;
        protected global::System.Web.UI.WebControls.Literal litStatus;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficulty;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.FileUpload fileImage;
        protected global::System.Web.UI.WebControls.Image imgCurrent;
        protected global::System.Web.UI.WebControls.HiddenField hidQuestions;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnToggle;
    }
}
