//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Quiz
{
    public partial class Leaderboard
    {
        /// <summary>
        /// ddlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlQuiz;

        /// <summary>
        /// lblNoQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNoQuizzes;

        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// pnlBoard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBoard;

        /// <summary>
        /// rptBoard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBoard;
    }
}
