//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Quiz
{
    public partial class List
    {
        /// <summary>
        /// ddlDifficulty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDifficulty;

        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// rptQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuizzes;
    }
}
