//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Quiz
{
    public partial class MyProgress
    {
        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// lnkTakeQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkTakeQuiz;

        /// <summary>
        /// phStats control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phStats;

        /// <summary>
        /// litQuizzes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litQuizzes;

        /// <summary>
        /// litBest control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litBest;

        /// <summary>
        /// litTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>
        /// rptScores control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptScores;
    }
}
