//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Quiz
{
    public partial class StudentProgress
    {
        protected global::System.Web.UI.WebControls.Literal litStudents;
        protected global::System.Web.UI.WebControls.Literal litActive;
        protected global::System.Web.UI.WebControls.Literal litAttempts;
        protected global::System.Web.UI.WebControls.Label lblEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptStudents;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal litDetailName;
        protected global::System.Web.UI.WebControls.Repeater rptAttempts;
    }
}
