//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Quiz
{
    public partial class Take
    {
        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// lblBadge control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBadge;

        /// <summary>
        /// pnlQuiz control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// pnlPreview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPreview;

        /// <summary>
        /// rptQuestions control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        /// <summary>
        /// btnSubmit control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;

        /// <summary>
        /// pnlResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResult;

        /// <summary>
        /// litName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litName;

        /// <summary>
        /// litCorrect control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCorrect;

        /// <summary>
        /// litTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTotal;

        /// <summary>
        /// litPoints control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPoints;
    }
}
