//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Admin
{
    public partial class ManageUsers
    {
        /// <summary>
        /// gvUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
