//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Topics
{
    public partial class Create
    {
        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBody;

        /// <summary>
        /// fileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fileImage;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
