//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Topics
{
    public partial class Details
    {
        /// <summary>
        /// litTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitle;

        /// <summary>
        /// imgCover control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCover;

        /// <summary>
        /// litBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label litBody;
    }
}
