//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Topics
{
    public partial class List
    {
        /// <summary>
        /// lblEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmpty;

        /// <summary>
        /// rptTopics control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTopics;
    }
}
