//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Hardware
{
    public partial class Details
    {
        /// <summary>
        /// litName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litName;

        /// <summary>
        /// imgPart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgPart;

        /// <summary>
        /// litDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label litDesc;
    }
}
