//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hardwarequest.Hardware
{
    public partial class Edit
    {
        /// <summary>
        /// lblError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// txtName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtName;

        /// <summary>
        /// txtDesc control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesc;

        /// <summary>
        /// txtPartKey control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPartKey;

        /// <summary>
        /// imgCurrent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCurrent;

        /// <summary>
        /// fileImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fileImage;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
